# Generated by Django 5.1.7 on 2025-03-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatupapp', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user',
            new_name='sender',
        ),
    ]
