# Generated by Django 5.1.7 on 2025-06-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatupapp', '0003_rename_user_messages_sender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
