# Generated by Django 5.1.7 on 2025-06-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatupapp', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='messages',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['room_name'], name='chatupapp_m_room_na_1fc99d_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['sender'], name='chatupapp_m_sender__8ad3f3_idx'),
        ),
    ]
