# Generated by Django 5.1.7 on 2025-06-12 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatupapp', '0005_alter_messages_options_messages_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
